### ISSUE TITLE
About the performance of BCSS dataset

### ISSUE THREAD

**Issue by o0t1ng0o** [pengsl-lab/DHUnet#1]
Hi @pengsl-lab,

Thank you for sharing your code.
I have tried to reimplement the performance of BCSS dataset.
```
python3 train.py --dataset BCSS --network DHUnet \
--cfg configs/DHUnet_224.yaml --root_path data \
--max_epochs 150 --output_dir model-BCSS/DHUnet \
--img_size 224 --base_lr 0.005 --batch_size 24
```

But I found that I can only get this performance : mean dice 0.562457 yc 0.461954 acc 0.774036
And the results in your paper is as follows:
![image](https://github.com/pengsl-lab/DHUnet/assets/16815652/ea8c8a8a-c606-4e83-9a22-4c10b3e27fd0)

Is there any problem about my reimplementation?

Thank you in advance!

**Comment by pengsl-lab** [comment]
According to BCSS reference, we tried the Class grouping and Train-test splits procedures.
1、Not all classes are used, mapping pixels into five region classes: tumor, stroma, inflammatory infiltration, necrosis and others. (This may be the reason for the dissatisfied effect.)
2、Use an unseen testing set to report performance: OL, LL, E2, EW, GM, and S3.
Our preprocessed data and trained model are publicly available at [https://drive.google.com/drive/folders/1cEHr1YPE3fuJ0AKlJtWHOZ_vLKMcdQPa?usp=sharing]. Please feel free to contact me if you have any further questions.

**Comment by guascy666** [comment]
i have the same problem with the above one。i have used your trained model but the acc result is only about 0.85。
